server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: demo

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /api-docs

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl